services:
  muninn:
    build: .
    container_name: muninn
    stdin_open: true
    tty: true
    volumes:
      - ./.env:/app/.env:ro
      - ./credentials.json:/app/credentials.json:ro
      - ./token.json:/app/token.json:rw
    restart: unless-stopped